# Generated by Django 4.0.2 on 2022-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We Leave A Delicious Memory For You', max_length=250)),
                ('description', models.TextField()),
                ('youtube_link', models.URLField(verbose_name='Youtube Video Link')),
            ],
            options={
                'verbose_name': 'About-us',
                'verbose_name_plural': 'About-us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.IntegerField(default=1, unique=True)),
                ('picture', models.ImageField(upload_to='about-us/')),
            ],
            options={
                'verbose_name': 'About-us Image',
                'verbose_name_plural': 'About-us Images',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(default=1, unique=True)),
                ('picture', models.ImageField(upload_to='slides/')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
