# Generated by Django 4.0.2 on 2022-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_chefsocials_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefsocials',
            name='picture',
        ),
        migrations.AddField(
            model_name='chef',
            name='picture',
            field=models.ImageField(null=True, upload_to='chefs/', verbose_name='Chef profile photo'),
        ),
    ]
