# Generated by Django 4.0.2 on 2022-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_chef_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefsocials',
            name='social_name',
            field=models.CharField(max_length=100, verbose_name='Social account name (this use for icon if is not showing icon search in www.fontawesome.com )'),
        ),
    ]
