# Generated by Django 4.0.2 on 2022-04-11 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
