# Generated by Django 4.0.2 on 2022-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitems_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='show_menu',
            field=models.BooleanField(default=False, verbose_name='show in menu tab'),
        ),
    ]
